apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-w09-aks
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: AZURE_CONTAINER_REGISTRY/frontend:latest # replace with your ACR
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w09-aks
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # Cluster-wide port
      targetPort: 80  # Container port
  type: LoadBalancer  # Expose via cloud load balancer (AKS will assign a public IP)
