name: CI - Build and Test

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services with Docker Compose
        run: docker compose -f ./example-3/docker-compose.yml up -d --build

      - name: Wait for DB
        run: sleep 20

      - name: Run backend tests
        run: docker exec product_api_container pytest /app/tests

      - name: Tear down
        run: docker compose -f ./example-3/docker-compose.yml down -v
